name: publish
on: [push]
jobs:
       publish-opl-api-image:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@v2
                     - name: Login to GitHub Container Registry
                       uses: docker/login-action@v1
                       with:
                            registry: ghcr.io
                            username: ${{ github.actor }}
                            password: ${{ secrets.GITHUB_TOKEN }}
                     - name: Set current date as env variable
                       id: datetime
                       run: echo "NOW=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
                     - name: Build the opl-api docker image
                       run: |
                            docker build . --tag ghcr.io/vatsaaa/opl-api-image-$NOW:latest
                            docker push ghcr.io/vatsaaa/opl-api-image-$NOW:latest